name: Spoke
favicon: null
layout_spectrum: 0.592313916888088
typography_spectrum: 0.3574729156680405
title: Spoke Phone
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fc6a3e'
    - '#fd8862'
    - '#f4baa4'
    - '#fed0c2'
  brandStrength: 0.375
  lightness: 0.8890990195795894
  saturation: 0.26586197689175606
  rhythmicContrast: 0.75
purpose: []
