name: Spoke
favicon: null
layout_spectrum: 0.716548963682726
typography_spectrum: 0.3574729156680405
title: 'Spoke - Calling people is about to get way easier!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.8068646844476461
  lightness: 0.75195860886015
  saturation: 0.9368237960152328
  rhythmicContrast: 0.9516590693965554
purpose: []
